# coding: utf-8

"""
    qTest Manager API Version 11.0.0 - 2023.6

    qTest Manager API Version 11.0.0 - 2023.6  # noqa: E501

    OpenAPI spec version: 11.0.0 - 2023.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ShortTestLogResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'id': 'int',
        'tester': 'str',
        'exe_start_date': 'datetime',
        'exe_end_date': 'datetime'
    }

    attribute_map = {
        'status': 'status',
        'id': 'id',
        'tester': 'tester',
        'exe_start_date': 'exe_start_date',
        'exe_end_date': 'exe_end_date'
    }

    def __init__(self, status=None, id=None, tester=None, exe_start_date=None, exe_end_date=None, _configuration=None):  # noqa: E501
        """ShortTestLogResource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._id = None
        self._tester = None
        self._exe_start_date = None
        self._exe_end_date = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if id is not None:
            self.id = id
        if tester is not None:
            self.tester = tester
        if exe_start_date is not None:
            self.exe_start_date = exe_start_date
        if exe_end_date is not None:
            self.exe_end_date = exe_end_date

    @property
    def status(self):
        """Gets the status of this ShortTestLogResource.  # noqa: E501


        :return: The status of this ShortTestLogResource.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ShortTestLogResource.


        :param status: The status of this ShortTestLogResource.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def id(self):
        """Gets the id of this ShortTestLogResource.  # noqa: E501


        :return: The id of this ShortTestLogResource.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ShortTestLogResource.


        :param id: The id of this ShortTestLogResource.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def tester(self):
        """Gets the tester of this ShortTestLogResource.  # noqa: E501

        Email of QA who is assigned this test-run  # noqa: E501

        :return: The tester of this ShortTestLogResource.  # noqa: E501
        :rtype: str
        """
        return self._tester

    @tester.setter
    def tester(self, tester):
        """Sets the tester of this ShortTestLogResource.

        Email of QA who is assigned this test-run  # noqa: E501

        :param tester: The tester of this ShortTestLogResource.  # noqa: E501
        :type: str
        """

        self._tester = tester

    @property
    def exe_start_date(self):
        """Gets the exe_start_date of this ShortTestLogResource.  # noqa: E501


        :return: The exe_start_date of this ShortTestLogResource.  # noqa: E501
        :rtype: datetime
        """
        return self._exe_start_date

    @exe_start_date.setter
    def exe_start_date(self, exe_start_date):
        """Sets the exe_start_date of this ShortTestLogResource.


        :param exe_start_date: The exe_start_date of this ShortTestLogResource.  # noqa: E501
        :type: datetime
        """

        self._exe_start_date = exe_start_date

    @property
    def exe_end_date(self):
        """Gets the exe_end_date of this ShortTestLogResource.  # noqa: E501


        :return: The exe_end_date of this ShortTestLogResource.  # noqa: E501
        :rtype: datetime
        """
        return self._exe_end_date

    @exe_end_date.setter
    def exe_end_date(self, exe_end_date):
        """Sets the exe_end_date of this ShortTestLogResource.


        :param exe_end_date: The exe_end_date of this ShortTestLogResource.  # noqa: E501
        :type: datetime
        """

        self._exe_end_date = exe_end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShortTestLogResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShortTestLogResource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShortTestLogResource):
            return True

        return self.to_dict() != other.to_dict()
