# coding: utf-8

"""
    qTest Manager API Version 11.0.0 - 2023.6

    qTest Manager API Version 11.0.0 - 2023.6  # noqa: E501

    OpenAPI spec version: 11.0.0 - 2023.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TestCaseWithNoCustomFieldResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'list[Link]',
        'id': 'int',
        'name': 'str',
        'order': 'int',
        'pid': 'str',
        'created_date': 'datetime',
        'last_modified_date': 'datetime',
        'web_url': 'str',
        'parent_id': 'int',
        'test_case_version_id': 'int',
        'version': 'str',
        'description': 'str',
        'precondition': 'str',
        'creator_id': 'int',
        'agent_ids': 'list[int]',
        'test_steps': 'list[TestStepWithNoCustomFieldsResource]'
    }

    attribute_map = {
        'links': 'links',
        'id': 'id',
        'name': 'name',
        'order': 'order',
        'pid': 'pid',
        'created_date': 'created_date',
        'last_modified_date': 'last_modified_date',
        'web_url': 'web_url',
        'parent_id': 'parent_id',
        'test_case_version_id': 'test_case_version_id',
        'version': 'version',
        'description': 'description',
        'precondition': 'precondition',
        'creator_id': 'creator_id',
        'agent_ids': 'agent_ids',
        'test_steps': 'test_steps'
    }

    def __init__(self, links=None, id=None, name=None, order=None, pid=None, created_date=None, last_modified_date=None, web_url=None, parent_id=None, test_case_version_id=None, version=None, description=None, precondition=None, creator_id=None, agent_ids=None, test_steps=None, _configuration=None):  # noqa: E501
        """TestCaseWithNoCustomFieldResource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._links = None
        self._id = None
        self._name = None
        self._order = None
        self._pid = None
        self._created_date = None
        self._last_modified_date = None
        self._web_url = None
        self._parent_id = None
        self._test_case_version_id = None
        self._version = None
        self._description = None
        self._precondition = None
        self._creator_id = None
        self._agent_ids = None
        self._test_steps = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if order is not None:
            self.order = order
        if pid is not None:
            self.pid = pid
        if created_date is not None:
            self.created_date = created_date
        if last_modified_date is not None:
            self.last_modified_date = last_modified_date
        if web_url is not None:
            self.web_url = web_url
        if parent_id is not None:
            self.parent_id = parent_id
        if test_case_version_id is not None:
            self.test_case_version_id = test_case_version_id
        if version is not None:
            self.version = version
        if description is not None:
            self.description = description
        if precondition is not None:
            self.precondition = precondition
        if creator_id is not None:
            self.creator_id = creator_id
        if agent_ids is not None:
            self.agent_ids = agent_ids
        if test_steps is not None:
            self.test_steps = test_steps

    @property
    def links(self):
        """Gets the links of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Link to resource  # noqa: E501

        :return: The links of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this TestCaseWithNoCustomFieldResource.

        Link to resource  # noqa: E501

        :param links: The links of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: list[Link]
        """

        self._links = links

    @property
    def id(self):
        """Gets the id of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        ID of the Test Case  # noqa: E501

        :return: The id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TestCaseWithNoCustomFieldResource.

        ID of the Test Case  # noqa: E501

        :param id: The id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Name of the Test Case  # noqa: E501

        :return: The name of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TestCaseWithNoCustomFieldResource.

        Name of the Test Case  # noqa: E501

        :param name: The name of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 500):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `500`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def order(self):
        """Gets the order of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Display order of the Test Case  # noqa: E501

        :return: The order of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this TestCaseWithNoCustomFieldResource.

        Display order of the Test Case  # noqa: E501

        :param order: The order of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def pid(self):
        """Gets the pid of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        PID of the Test Case  # noqa: E501

        :return: The pid of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._pid

    @pid.setter
    def pid(self, pid):
        """Sets the pid of this TestCaseWithNoCustomFieldResource.

        PID of the Test Case  # noqa: E501

        :param pid: The pid of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """

        self._pid = pid

    @property
    def created_date(self):
        """Gets the created_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501


        :return: The created_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this TestCaseWithNoCustomFieldResource.


        :param created_date: The created_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def last_modified_date(self):
        """Gets the last_modified_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501


        :return: The last_modified_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date):
        """Sets the last_modified_date of this TestCaseWithNoCustomFieldResource.


        :param last_modified_date: The last_modified_date of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: datetime
        """

        self._last_modified_date = last_modified_date

    @property
    def web_url(self):
        """Gets the web_url of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Web URL of the Test Case  # noqa: E501

        :return: The web_url of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._web_url

    @web_url.setter
    def web_url(self, web_url):
        """Sets the web_url of this TestCaseWithNoCustomFieldResource.

        Web URL of the Test Case  # noqa: E501

        :param web_url: The web_url of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """

        self._web_url = web_url

    @property
    def parent_id(self):
        """Gets the parent_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Module ID of the Test Case  # noqa: E501

        :return: The parent_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this TestCaseWithNoCustomFieldResource.

        Module ID of the Test Case  # noqa: E501

        :param parent_id: The parent_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: int
        """

        self._parent_id = parent_id

    @property
    def test_case_version_id(self):
        """Gets the test_case_version_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        ID of Test Case Version  # noqa: E501

        :return: The test_case_version_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: int
        """
        return self._test_case_version_id

    @test_case_version_id.setter
    def test_case_version_id(self, test_case_version_id):
        """Sets the test_case_version_id of this TestCaseWithNoCustomFieldResource.

        ID of Test Case Version  # noqa: E501

        :param test_case_version_id: The test_case_version_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: int
        """

        self._test_case_version_id = test_case_version_id

    @property
    def version(self):
        """Gets the version of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Test Case Version of the Test Case  # noqa: E501

        :return: The version of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this TestCaseWithNoCustomFieldResource.

        Test Case Version of the Test Case  # noqa: E501

        :param version: The version of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def description(self):
        """Gets the description of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Description of the Test Case  # noqa: E501

        :return: The description of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TestCaseWithNoCustomFieldResource.

        Description of the Test Case  # noqa: E501

        :param description: The description of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def precondition(self):
        """Gets the precondition of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Precondition of the Test Case  # noqa: E501

        :return: The precondition of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: str
        """
        return self._precondition

    @precondition.setter
    def precondition(self, precondition):
        """Sets the precondition of this TestCaseWithNoCustomFieldResource.

        Precondition of the Test Case  # noqa: E501

        :param precondition: The precondition of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: str
        """

        self._precondition = precondition

    @property
    def creator_id(self):
        """Gets the creator_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        ID of the User who create the Test Case  # noqa: E501

        :return: The creator_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: int
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """Sets the creator_id of this TestCaseWithNoCustomFieldResource.

        ID of the User who create the Test Case  # noqa: E501

        :param creator_id: The creator_id of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: int
        """

        self._creator_id = creator_id

    @property
    def agent_ids(self):
        """Gets the agent_ids of this TestCaseWithNoCustomFieldResource.  # noqa: E501


        :return: The agent_ids of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: list[int]
        """
        return self._agent_ids

    @agent_ids.setter
    def agent_ids(self, agent_ids):
        """Sets the agent_ids of this TestCaseWithNoCustomFieldResource.


        :param agent_ids: The agent_ids of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: list[int]
        """

        self._agent_ids = agent_ids

    @property
    def test_steps(self):
        """Gets the test_steps of this TestCaseWithNoCustomFieldResource.  # noqa: E501

        Arrays of Test Step of the Test Case  # noqa: E501

        :return: The test_steps of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :rtype: list[TestStepWithNoCustomFieldsResource]
        """
        return self._test_steps

    @test_steps.setter
    def test_steps(self, test_steps):
        """Sets the test_steps of this TestCaseWithNoCustomFieldResource.

        Arrays of Test Step of the Test Case  # noqa: E501

        :param test_steps: The test_steps of this TestCaseWithNoCustomFieldResource.  # noqa: E501
        :type: list[TestStepWithNoCustomFieldsResource]
        """

        self._test_steps = test_steps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestCaseWithNoCustomFieldResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCaseWithNoCustomFieldResource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TestCaseWithNoCustomFieldResource):
            return True

        return self.to_dict() != other.to_dict()
