# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_network import ai_network_types_pb2 as ai__network_dot_ai__network__types__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_network/ai_network_utils_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AINetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAINetworkStatus = channel.unary_unary(
                '/AINetwork/GetAINetworkStatus',
                request_serializer=ai__network_dot_ai__network__types__pb2.NetworkStatusRequest.SerializeToString,
                response_deserializer=ai__network_dot_ai__network__types__pb2.NetworkStatusResponse.FromString,
                _registered_method=True)


class AINetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAINetworkStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AINetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAINetworkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAINetworkStatus,
                    request_deserializer=ai__network_dot_ai__network__types__pb2.NetworkStatusRequest.FromString,
                    response_serializer=ai__network_dot_ai__network__types__pb2.NetworkStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AINetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AINetwork', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AINetwork(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAINetworkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AINetwork/GetAINetworkStatus',
            ai__network_dot_ai__network__types__pb2.NetworkStatusRequest.SerializeToString,
            ai__network_dot_ai__network__types__pb2.NetworkStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
