# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai-network/ai_network_utils.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai_network import ai_network_types_pb2 as ai__network_dot_ai__network__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ai-network/ai_network_utils.proto\x1a!ai-network/ai_network_types.proto2~\n\tAINetwork\x12q\n\x12GetAINetworkStatus\x12,.ai_network_types.proto.NetworkStatusRequest\x1a-.ai_network_types.proto.NetworkStatusResponseB\x18Z\x16\x61i-network/utils;utilsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_network.ai_network_utils_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026ai-network/utils;utils'
  _globals['_AINETWORK']._serialized_start=72
  _globals['_AINETWORK']._serialized_end=198
# @@protoc_insertion_point(module_scope)
