import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_9bcc22b65c(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_ca7819e8b2():spartaqube_cli.list()
@app.command()
def sparta_5fc6b5adde():spartaqube_cli.sparta_5fc6b5adde()
@app.command()
def sparta_958ca2a3b8():print('Hello world!')
if __name__=='__main__':app()