# coding: utf-8

"""
    qTest Manager API Version 11.0.0 - 2023.6

    qTest Manager API Version 11.0.0 - 2023.6  # noqa: E501

    OpenAPI spec version: 11.0.0 - 2023.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.automation_job_api import AutomationJobApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutomationJobApi(unittest.TestCase):
    """AutomationJobApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.automation_job_api.AutomationJobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_schedule(self):
        """Test case for create_schedule

        Create a Schedule  # noqa: E501
        """
        pass

    def test_search_automation_agents(self):
        """Test case for search_automation_agents

        Search automation agents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
