import logging
from . import Field as Field, GetResult as GetResult, PropertyValue as PropertyValue
from .msg import msg as msg
from typing import Any

console = logging

class Property:
    def __real_init__(self, /, __internal: bool = False) -> None: ...
    def __init__(self, *args) -> None: ...
    def valueOf(self) -> PropertyValue: ...
    def on_update(self, f: Any = None) -> None: ...
    def create(self) -> None: ...
    def recall(self) -> PropertyValue: ...
    def __iter__(self) -> None: ...
