"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GetResourceSettingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_ID_FIELD_NUMBER: builtins.int
    RESPONSE_JSON_PATH_FIELD_NUMBER: builtins.int
    resource_id: builtins.str
    """Resource ID whose settings are being requested."""
    @property
    def response_json_path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Empty list means full settings."""
    def __init__(
        self,
        *,
        resource_id: builtins.str = ...,
        response_json_path: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["resource_id", b"resource_id", "response_json_path", b"response_json_path"]) -> None: ...

global___GetResourceSettingsRequest = GetResourceSettingsRequest

@typing_extensions.final
class UpdateResourceSettingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_ID_FIELD_NUMBER: builtins.int
    RESPONSE_JSON_PATH_FIELD_NUMBER: builtins.int
    JSON_PATCH_FIELD_NUMBER: builtins.int
    resource_id: builtins.str
    """Resource ID whose settings are being updated."""
    @property
    def response_json_path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Empty list means full settings."""
    json_patch: builtins.str
    """Serialized JSON Patch (https://tools.ietf.org/html/rfc6902)."""
    def __init__(
        self,
        *,
        resource_id: builtins.str = ...,
        response_json_path: collections.abc.Iterable[builtins.str] | None = ...,
        json_patch: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["json_patch", b"json_patch", "resource_id", b"resource_id", "response_json_path", b"response_json_path"]) -> None: ...

global___UpdateResourceSettingsRequest = UpdateResourceSettingsRequest

@typing_extensions.final
class ResourceSettingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JSON_FIELD_NUMBER: builtins.int
    json: builtins.str
    """JSON-serialized resource settings."""
    def __init__(
        self,
        *,
        json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["json", b"json"]) -> None: ...

global___ResourceSettingsResponse = ResourceSettingsResponse
