# API Reference {.doc .doc-index}

## CaML Core

Core Classes

| | |
| --- | --- |
| [CamlDML](CamlDML.qmd#caml.CamlDML) | The CamlDML class represents a Double Machine Learning (DML) implementation for estimating... |
| [CamlPolicy](CamlPolicy.qmd#caml.CamlPolicy) | The CamlPolicy class represents a Policy Learning implementation for estimating... |
| [CamlEnsemble](CamlEnsemble.qmd#caml.CamlEnsemble) | The CamlEnsemble class represents a Ensemble Learning implementation for estimating... |
| [CamlDRL](CamlDRL.qmd#caml.CamlDRL) | The CamlDRL class represents a Doubly Robust Learning (DRL) implementation for estimating... |
| [CamlDynamic](CamlDynamic.qmd#caml.CamlDynamic) | The CamlDynamic class represents a dynamic (time) implementation for estimating... |

## Core Extensions

Plotting

| | |
| --- | --- |
| [extensions.plots.plot](extensions.plots.plot.qmd#caml.extensions.plots.plot) | A plot. |

## Developer Tools

Utilities, Descriptors, & Validators

| | |
| --- | --- |
| [utils.generate_random_string](utils.generate_random_string.qmd#caml.utils.generate_random_string) | Function to generate a random string of ascii lowercase letters and digits of length N. |
| [utils.descriptors.ValidDataFrame](utils.descriptors.ValidDataFrame.qmd#caml.utils.descriptors.ValidDataFrame) | Descriptor class that allows setting and getting a value that must be a valid DataFrame |
| [utils.descriptors.ValidSparkSession](utils.descriptors.ValidSparkSession.qmd#caml.utils.descriptors.ValidSparkSession) | Descriptor class for a valid SparkSession object. |
| [utils.descriptors.ValidSklearnModel](utils.descriptors.ValidSklearnModel.qmd#caml.utils.descriptors.ValidSklearnModel) | Descriptor class for a valid nuissance Sklearn model object. |
| [utils.descriptors.ValidBoolean](utils.descriptors.ValidBoolean.qmd#caml.utils.descriptors.ValidBoolean) | Descriptor class for a valid boolean value. |
| [utils.descriptors.ValidString](utils.descriptors.ValidString.qmd#caml.utils.descriptors.ValidString) | Descriptor class for a valid string value. |
| [utils.descriptors.ValidFeatureList](utils.descriptors.ValidFeatureList.qmd#caml.utils.descriptors.ValidFeatureList) | Descriptor class for a valid str, list, or tuple feature names. |