depends = ('ITKPyBase', 'ITKCommon', 'ITKCommon', )
templates = (  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS2IUS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2ISS2', True, 'itk::Image< unsigned short,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2IUC2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2ISS2', True, 'itk::Image< double,2 >, itk::Image< signed short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2IUC2', True, 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID2IUS2', True, 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterISS3IUS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3ISS3', True, 'itk::Image< unsigned short,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3IUC3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3ISS3', True, 'itk::Image< double,3 >, itk::Image< signed short,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3IUC3', True, 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('DissolveMaskImageFilter', 'itk::DissolveMaskImageFilter', 'itkDissolveMaskImageFilterID3IUS3', True, 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
)
factories = ()
