
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-20T11:29:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dd7d7b03412a2d5a1ebc30ad3f02558bb459913",
 "version": "2.43.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
