
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-21T17:06:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "79af0a51d53802976cee43ba73e8dc7e5b4f648a",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
