import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_662923f025(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_0ed7bdf6f3():spartaqube_cli.list()
@app.command()
def sparta_f5be1a18c1():spartaqube_cli.sparta_f5be1a18c1()
@app.command()
def sparta_e2583ab2a6():print('Hello world!')
if __name__=='__main__':app()