import logging
from . import Field as Field, GetResult as GetResult, PropertyValue as PropertyValue
from .Item import Item as Item
from .Slice import Slice as Slice
from .msg import msg as msg
from asyncio import Task
from collections import deque as deque
from itertools import dropwhile as dropwhile, islice as islice
from typing import Any
from typing_extensions import TypeAlias

console = logging
PythonClass: TypeAlias

class List:
    def __init__(self, *args: Any) -> None: ...
    def of_type(self) -> Item: ...
    @property
    def of_item(self) -> Item: ...
    @property
    def fields(self) -> List: ...
    @property
    def type(self) -> List: ...
    def __len__(self) -> int: ...
    def on_update(self, f: Any) -> None: ...
    def prepend(self, item: list[Item] | Item | List, before: bool = True, relative_to_item: Item | None = None) -> None: ...
    def append(self, item: list[Item] | Item | List, before: bool = False, relative_to_item: Item | None = None) -> None: ...
    def remove(self, item: Item) -> None: ...
    def destroy(self, item: Item) -> None: ...
    def create_async(self, set_fields: list[str | dict[str, PropertyValue]] | str | dict[str, PropertyValue] | None = None, field_name: str | None = 'name') -> Task['"Item" | list']: ...
    def create(self, set_fields: list[str | dict[str, PropertyValue]] | str | dict[str, PropertyValue] | None = None, field_name: str | None = 'name') -> Item | list: ...
    def first(self) -> Item | None: ...
    def item_before(self, item: Item) -> Item: ...
    def item_after(self, item: Item) -> Item | None: ...
    def last(self) -> Item | None: ...
    def find(self, search_for: Item | List | PropertyValue, search_in_field: str | Item | List | None = None) -> Item | None: ...
    def __getitem__(self, search_term: str) -> Item | None: ...
    class __rnIterator:
        index: int
        def __init__(self, r_n_o: List) -> None: ...
        def __next__(self) -> Item: ...
    def recall(self) -> List: ...
    def __iter__(self) -> __rnIterator: ...
    def slice(self, start_at: Item | None = None, size: int = 16, search_term: Any | None = None, search_field: str | None = None) -> Slice | None: ...
    def define_property(self, property_name: str, data_type: str | PythonClass | None = None) -> Item: ...
    def define_calculated_property(self, property_name: str, data_type: str, formula: str) -> Item: ...
    def define_subitem(self, link_name: str, inverse_name: str | None = None) -> Item: ...
    def define_link(self, link_name: str, range: str | None = None, inverse_name: str | None = None, inverse_link_or_list: str | None = 'list', inverse_range: str | None = None) -> Item: ...
    def define_calculated_link(self, link_name: str, range: str, formula: str, inverse_name: str | None = None) -> Item: ...
    def define_list_of_items(self, list_name: str, inverse_name: str | None = None) -> Item: ...
    def define_list_of_links(self, list_name: str, range: str | None = None, inverse_name: str | None = None, inverse_link_or_list: str | None = 'link', inverse_range: str | None = None) -> Item: ...
    def define_list(self, list_name: str, range: str | None = None, inverse_name: str | None = None, inverse_link_or_list: str | None = 'link', inverse_range: str | None = None) -> Item: ...
    def define_calculated_list(self, list_name: str, range: str, formula: str, inverse_name: str | None = None) -> Item: ...
    def move_first(self, item: Item) -> None: ...
    def move_last(self, item: Item) -> None: ...
    def move_next(self, item: Item) -> None: ...
    def move_prev(self, item: Item) -> None: ...
    def move_before(self, item_to_move: Item, before_item: Item) -> None: ...
    def move_after(self, item: Item, after_item: Item) -> None: ...
    def move(self, item: Item, before_or_after: str, relative_to_item: Item | None = None) -> None: ...
    def append_before(self, item: list[Item] | Item | List, before_item: Item | None = None) -> None: ...
    def append_after(self, item: list[Item] | Item | List, after_item: Item | None = None) -> None: ...
