from .script01 import Script01

class Scripted(Script01):

    TRACKER01 = "Targeted IP         : {}"
    TRACKER02 = "IP type             : {}"
    TRACKER03 = "Country             : {}"
    TRACKER04 = "Country Code        : {}"
    TRACKER05 = "City                : {}"
    TRACKER06 = "Continent           : {}"
    TRACKER07 = "Continent Code      : {}"
    TRACKER07 = "Region              : {}"
    TRACKER09 = "Region Code         : {}"
    TRACKER10 = "Latitude            : {}"
    TRACKER11 = "Longitude           : {}"
    TRACKER12 = "EU                  : {}"
    TRACKER13 = "Postal              : {}"
    TRACKER14 = "Calling Code        : {}"
    TRACKER15 = "Capital             : {}"
    TRACKER16 = "Borders             : {}"
    TRACKER17 = "Country Flag        : {}"
    TRACKER18 = "ASN                 : {}"
    TRACKER19 = "ORG                 : {}"
    TRACKER20 = "ISP                 : {}"
    TRACKER21 = "Domain              : {}"
    TRACKER22 = "ID                  : {}"
    TRACKER23 = "ABBR                : {}"
    TRACKER24 = "DST                 : {}"
    TRACKER25 = "Offset              : {}"
    TRACKER26 = "UTC                 : {}"
    TRACKER27 = "Current Time        : {}"
    TRACKER28 = "Maps                : {}"
