# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from datasphere.yandex.cloud.priv.datasphere.v2 import archive_project_storage_service_pb2 as yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2
from datasphere.yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2


class ArchiveProjectStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ArchiveStorage = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.ArchiveProjectStorageService/ArchiveStorage',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.ArchiveStorageRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.UnarchiveStorage = channel.unary_unary(
                '/yandex.cloud.priv.datasphere.v2.ArchiveProjectStorageService/UnarchiveStorage',
                request_serializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.UnarchiveStorageRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )


class ArchiveProjectStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ArchiveStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnarchiveStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveProjectStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ArchiveStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveStorage,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.ArchiveStorageRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'UnarchiveStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.UnarchiveStorage,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.UnarchiveStorageRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.datasphere.v2.ArchiveProjectStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArchiveProjectStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ArchiveStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.datasphere.v2.ArchiveProjectStorageService/ArchiveStorage',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.ArchiveStorageRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnarchiveStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.datasphere.v2.ArchiveProjectStorageService/UnarchiveStorage',
            yandex_dot_cloud_dot_priv_dot_datasphere_dot_v2_dot_archive__project__storage__service__pb2.UnarchiveStorageRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
