
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-21T11:22:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a60046461970efac229190dc5fddd6dbb86746b",
 "version": "8.18.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
