"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import datasphere.yandex.cloud.priv.iam.v1.os_login_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GetOsLoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLOUD_ID_FIELD_NUMBER: builtins.int
    SUBJECT_ID_FIELD_NUMBER: builtins.int
    OS_LOGIN_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    cloud_id: builtins.str
    subject_id: builtins.str
    os_login: builtins.str
    uid: builtins.int
    def __init__(
        self,
        *,
        cloud_id: builtins.str = ...,
        subject_id: builtins.str = ...,
        os_login: builtins.str = ...,
        uid: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["os_login", b"os_login", "subject", b"subject", "subject_id", b"subject_id", "uid", b"uid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cloud_id", b"cloud_id", "os_login", b"os_login", "subject", b"subject", "subject_id", b"subject_id", "uid", b"uid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["subject", b"subject"]) -> typing_extensions.Literal["subject_id", "os_login", "uid"] | None: ...

global___GetOsLoginRequest = GetOsLoginRequest

@typing_extensions.final
class UpdateOsLoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLOUD_ID_FIELD_NUMBER: builtins.int
    SUBJECT_ID_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    OS_LOGIN_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    cloud_id: builtins.str
    subject_id: builtins.str
    """use calling subject if not specified"""
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    os_login: builtins.str
    uid: builtins.int
    def __init__(
        self,
        *,
        cloud_id: builtins.str = ...,
        subject_id: builtins.str = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        os_login: builtins.str = ...,
        uid: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cloud_id", b"cloud_id", "os_login", b"os_login", "subject_id", b"subject_id", "uid", b"uid", "update_mask", b"update_mask"]) -> None: ...

global___UpdateOsLoginRequest = UpdateOsLoginRequest

@typing_extensions.final
class UpdateOsLoginMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLOUD_ID_FIELD_NUMBER: builtins.int
    SUBJECT_ID_FIELD_NUMBER: builtins.int
    cloud_id: builtins.str
    subject_id: builtins.str
    def __init__(
        self,
        *,
        cloud_id: builtins.str = ...,
        subject_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cloud_id", b"cloud_id", "subject_id", b"subject_id"]) -> None: ...

global___UpdateOsLoginMetadata = UpdateOsLoginMetadata

@typing_extensions.final
class ListOsLoginsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLOUD_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    cloud_id: builtins.str
    """ID of the cloud to search for os login in."""
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        cloud_id: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cloud_id", b"cloud_id", "page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListOsLoginsRequest = ListOsLoginsRequest

@typing_extensions.final
class ListOsLoginsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OS_LOGIN_INFOS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def os_login_infos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.priv.iam.v1.os_login_pb2.OsLoginInfo]: ...
    next_page_token: builtins.str
    def __init__(
        self,
        *,
        os_login_infos: collections.abc.Iterable[yandex.cloud.priv.iam.v1.os_login_pb2.OsLoginInfo] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token", b"next_page_token", "os_login_infos", b"os_login_infos"]) -> None: ...

global___ListOsLoginsResponse = ListOsLoginsResponse
