from enola import tracking
from enola.enola_types import ErrOrWarnKind
#from enola.base.enola_types import AgentResponseModel

#token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFTk9MQV9IVUVNVUwwNC1mYTIyOTZkNDBiYjUwMzNkYTdhZjE1N2JiMzUwYjc2ZiIsImlkIjoiZWFmMWJlOTUtMDFkNy00MzU5LTk4NDctMGE2NjBjNGEzMTE4IiwiZGlzcGxheU5hbWUiOiJOdWV2aXRhIDEiLCJhZ2VudERlcGxveUlkIjoiRU5PTEFfSFVFTVVMMDQtZmEyMjk2ZDQwYmI1MDMzZGE3YWYxNTdiYjM1MGI3NmYiLCJjYW5UcmFja2luZyI6dHJ1ZSwiY2FuRXZhbHVhdGUiOmZhbHNlLCJjYW5HZXRFeGVjdXRpb25zIjpmYWxzZSwidXJsIjoiaHR0cDovL2xvY2FsaG9zdDo3MDcyL2FwaSIsInVybEJhY2tlbmQiOiJodHRwOi8vbG9jYWxob3N0OjcwNzEvYXBpIiwib3JnSWQiOiJFTk9MQV9IVUVNVUwwNCIsImlzU2VydmljZUFjY291bnQiOnRydWUsImlhdCI6MTcxOTE2MjU2OCwiZXhwIjoxODQ1MjU5MjA4LCJpc3MiOiJlbm9sYSJ9.WYJbsHmtHYZ0CuzKZB4l0WfJVbHd4dAZRhRI0rIqYwk"
#token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFTk9MQV9IVUVNVUwwOC1lNGMzMDBiODM3NDk4M2U2NTU0OTVlZDQwYzMwNGUzYyIsImlkIjoiMDA2N2JiZjMtYzQ4My00ZjY4LTk4ZTItNzQyZTA4YzYwZDdjIiwiZGlzcGxheU5hbWUiOiJjdWVudGEgc2VydmljaW8gMiIsImFnZW50RGVwbG95SWQiOiJFTk9MQV9IVUVNVUwwOC1lNGMzMDBiODM3NDk4M2U2NTU0OTVlZDQwYzMwNGUzYyIsImNhblRyYWNraW5nIjp0cnVlLCJjYW5FdmFsdWF0ZSI6dHJ1ZSwiY2FuR2V0RXhlY3V0aW9ucyI6dHJ1ZSwidXJsIjoiaHR0cDovL2xvY2FsaG9zdDo3MDcyL2FwaSIsInVybEJhY2tlbmQiOiJodHRwOi8vbG9jYWxob3N0OjcwNzEvYXBpIiwib3JnSWQiOiJFTk9MQV9IVUVNVUwwOCIsImlzU2VydmljZUFjY291bnQiOnRydWUsImlhdCI6MTcyMTU4OTI0MiwiZXhwIjoxODQ3Njc4Mzk5LCJpc3MiOiJlbm9sYSJ9.7Fib2XbSaGuuiVYT-A1IYzCjtB1dt6CNkf5YeRKN5Xw"
#token enola-ia, prod ambiente 08
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFTk9MQV9IVUVNVUwwOC0xY2MzNjUwMTE0MGUzZjFmMWNkZWNlYjgwNjBhN2ZlZCIsImlkIjoiNmQ2YTY2ZjItMzkwMi00MzNhLTg1MjUtMmFlMzI1YmRkYTk2IiwiZGlzcGxheU5hbWUiOiIyMiIsImFnZW50RGVwbG95SWQiOiJFTk9MQV9IVUVNVUwwOC0xY2MzNjUwMTE0MGUzZjFmMWNkZWNlYjgwNjBhN2ZlZCIsImNhblRyYWNraW5nIjp0cnVlLCJjYW5FdmFsdWF0ZSI6dHJ1ZSwiY2FuR2V0RXhlY3V0aW9ucyI6dHJ1ZSwidXJsIjoiaHR0cHM6Ly9hcGlzZW5kLmVub2xhLWFpLmNvbS9hcGkiLCJ1cmxCYWNrZW5kIjoiaHR0cHM6Ly9hcGkuZW5vbGEtYWkuY29tL2FwaSIsIm9yZ0lkIjoiRU5PTEFfSFVFTVVMMDgiLCJpc1NlcnZpY2VBY2NvdW50Ijp0cnVlLCJpYXQiOjE3MjM4NDkyMDUsImV4cCI6MTg0OTkyNDc5OSwiaXNzIjoiZW5vbGEifQ.dTtuQapNayDr_ruMva6V76VKbEWYS3ULLht-70Eywqo"

myAgent = tracking.Tracking(token=token, name="Ejecución Score", is_test=True, message_input="Score Testing", external_id='123')


step1 = myAgent.new_step("step 1", message_input="como estás")

myAgent.close_step_others(step=step1,successfull=True, message_output="uno" )
myAgent.execute(successfull=True, score_value=0.87, score_group="A", score_cluster="1", score_date="2020-01-01", message_output="hola")



print(myAgent.agent_deploy_id)
print(myAgent.enola_id)
print(myAgent.url_evaluation_def_get)
print(myAgent.url_evaluation_post)
print(myAgent.tracking_status)
