###default __init__ 
__version__='1.0.0' 
 
from pathlib import Path
import sys
path = str(Path(Path(__file__).parent.absolute()).parent.absolute())
sys.path.insert(0, path)


from biopax.utils.class_utils import tostring

##from biopax.entityreference import Entityreference
from biopax.entityreference import EntityReference
##from biopax.pathwaystep import Pathwaystep
from biopax.pathwaystep import PathwayStep
##from biopax.degradation import Degradation
from biopax.degradation import Degradation
##from biopax.cellvocabulary import Cellvocabulary
from biopax.cellvocabulary import CellVocabulary
##from biopax.modificationfeature import Modificationfeature
from biopax.modificationfeature import ModificationFeature
##from biopax.dnaregion import Dnaregion
from biopax.dnaregion import DnaRegion
##from biopax.pathway import Pathway
from biopax.pathway import Pathway
##from biopax.templatereaction import Templatereaction
from biopax.templatereaction import TemplateReaction
##from biopax.transportwithbiochemicalreaction import Transportwithbiochemicalreaction
from biopax.transportwithbiochemicalreaction import TransportWithBiochemicalReaction
##from biopax.templatereactionregulation import Templatereactionregulation
from biopax.templatereactionregulation import TemplateReactionRegulation
##from biopax.physicalentity import Physicalentity
from biopax.physicalentity import PhysicalEntity
##from biopax.tissuevocabulary import Tissuevocabulary
from biopax.tissuevocabulary import TissueVocabulary
##from biopax.conversion import Conversion
from biopax.conversion import Conversion
##from biopax.phenotypevocabulary import Phenotypevocabulary
from biopax.phenotypevocabulary import PhenotypeVocabulary
##from biopax.covalentbindingfeature import Covalentbindingfeature
from biopax.covalentbindingfeature import CovalentBindingFeature
##from biopax.sequenceinterval import Sequenceinterval
from biopax.sequenceinterval import SequenceInterval
##from biopax.chemicalstructure import Chemicalstructure
from biopax.chemicalstructure import ChemicalStructure
##from biopax.rnaregionreference import Rnaregionreference
from biopax.rnaregionreference import RnaRegionReference
##from biopax.evidence import Evidence
from biopax.evidence import Evidence
##from biopax.rnaregion import Rnaregion
from biopax.rnaregion import RnaRegion
##from biopax.proteinreference import Proteinreference
from biopax.proteinreference import ProteinReference
##from biopax.xref import Xref
from biopax.xref import Xref
##from biopax.evidencecodevocabulary import Evidencecodevocabulary
from biopax.evidencecodevocabulary import EvidenceCodeVocabulary
##from biopax.biochemicalpathwaystep import Biochemicalpathwaystep
from biopax.biochemicalpathwaystep import BiochemicalPathwayStep
##from biopax.entityreferencetypevocabulary import Entityreferencetypevocabulary
from biopax.entityreferencetypevocabulary import EntityReferenceTypeVocabulary
##from biopax.kprime import Kprime
from biopax.kprime import KPrime
##from biopax.publicationxref import Publicationxref
from biopax.publicationxref import PublicationXref
##from biopax.molecularinteraction import Molecularinteraction
from biopax.molecularinteraction import MolecularInteraction
##from biopax.catalysis import Catalysis
from biopax.catalysis import Catalysis
##from biopax.dna import Dna
from biopax.dna import Dna
##from biopax.sequenceregionvocabulary import Sequenceregionvocabulary
from biopax.sequenceregionvocabulary import SequenceRegionVocabulary
##from biopax.sequencemodificationvocabulary import Sequencemodificationvocabulary
from biopax.sequencemodificationvocabulary import SequenceModificationVocabulary
##from biopax.smallmolecule import Smallmolecule
from biopax.smallmolecule import SmallMolecule
##from biopax.controlledvocabulary import Controlledvocabulary
from biopax.controlledvocabulary import ControlledVocabulary
##from biopax.stoichiometry import Stoichiometry
from biopax.stoichiometry import Stoichiometry
##from biopax.gene import Gene
from biopax.gene import Gene
##from biopax.dnaregionreference import Dnaregionreference
from biopax.dnaregionreference import DnaRegionReference
##from biopax.relationshiptypevocabulary import Relationshiptypevocabulary
from biopax.relationshiptypevocabulary import RelationshipTypeVocabulary
##from biopax.geneticinteraction import Geneticinteraction
from biopax.geneticinteraction import GeneticInteraction
##from biopax.experimentalformvocabulary import Experimentalformvocabulary
from biopax.experimentalformvocabulary import ExperimentalFormVocabulary
##from biopax.sequencesite import Sequencesite
from biopax.sequencesite import SequenceSite
##from biopax.cellularlocationvocabulary import Cellularlocationvocabulary
from biopax.cellularlocationvocabulary import CellularLocationVocabulary
##from biopax.provenance import Provenance
from biopax.provenance import Provenance
##from biopax.protein import Protein
from biopax.protein import Protein
##from biopax.dnareference import Dnareference
from biopax.dnareference import DnaReference
##from biopax.deltag import Deltag
from biopax.deltag import DeltaG
##from biopax.interactionvocabulary import Interactionvocabulary
from biopax.interactionvocabulary import InteractionVocabulary
##from biopax.smallmoleculereference import Smallmoleculereference
from biopax.smallmoleculereference import SmallMoleculeReference
##from biopax.complex import Complex
from biopax.complex import Complex
##from biopax.transport import Transport
from biopax.transport import Transport
##from biopax.interaction import Interaction
from biopax.interaction import Interaction
##from biopax.rna import Rna
from biopax.rna import Rna
##from biopax.experimentalform import Experimentalform
from biopax.experimentalform import ExperimentalForm
##from biopax.biosource import Biosource
from biopax.biosource import BioSource
##from biopax.rnareference import Rnareference
from biopax.rnareference import RnaReference
##from biopax.entityfeature import Entityfeature
from biopax.entityfeature import EntityFeature
##from biopax.complexassembly import Complexassembly
from biopax.complexassembly import ComplexAssembly
##from biopax.score import Score
from biopax.score import Score
##from biopax.biochemicalreaction import Biochemicalreaction
from biopax.biochemicalreaction import BiochemicalReaction
##from biopax.relationshipxref import Relationshipxref
from biopax.relationshipxref import RelationshipXref
##from biopax.bindingfeature import Bindingfeature
from biopax.bindingfeature import BindingFeature
##from biopax.fragmentfeature import Fragmentfeature
from biopax.fragmentfeature import FragmentFeature
##from biopax.modulation import Modulation
from biopax.modulation import Modulation
##from biopax.sequencelocation import Sequencelocation
from biopax.sequencelocation import SequenceLocation
##from biopax.control import Control
from biopax.control import Control
##from biopax.unificationxref import Unificationxref
from biopax.unificationxref import UnificationXref
######## unexpected name: <N00923931b629499784892fdc6f24c77f> 
######## unexpected name: <N185effadc9224babb1ac8aa365fe6124> 
##from biopax.entity import Entity
from biopax.entity import Entity
##from biopax.utilityclass import Utilityclass
from biopax.utilityclass import UtilityClass
######## unexpected name: <N0acf0844890745de9f5da6f58c664470> 
######## unexpected name: <N8a42eff7b21240b6aa8072548f7897c5> 
######## unexpected name: <N96bcc6af961c4125b3cc43c7dcf348ea> 
######## unexpected name: <Nddc3c2678368498aa1f5b7495f0d7fb3> 
######## unexpected name: <N26c741a3ddd740ab8f9b05c1102f9517> 
######## unexpected name: <N37b5ff65c5404dd7b1ae2e4c040c1254> 
######## unexpected name: <N2de6837a40f244858e311a9464c3e902> 
######## unexpected name: <N29e933bf0dd445339d17364772a201d3> 
######## unexpected name: <Nfa7e9257b8634bd58b5eb017a8edbe9c> 
######## unexpected name: <N369052350f99409cb1a10dcc34d5d1eb> 
######## unexpected name: <N957dbc35cc544fca80a8ab6efddd2ae7> 
######## unexpected name: <Ne117d6ab4446463ebd666668dd7c4d54> 
######## unexpected name: <N3e8f09f145ac41379eda4e625e0cddbe> 
######## unexpected name: <Na6f030dea06348bfbfd4267bdfb8c3ea> 
######## unexpected name: <N63ebffde0a0f436dbd529cf29ce28830> 
######## unexpected name: <N9fe4cf0b59854b6d9967855940a2247b> 
######## unexpected name: <N6ed3c2035ebc492b8965c5be2540213e> 
######## unexpected name: <Nb23c0c73b6d246a2aedc29b4becf8acf> 
######## unexpected name: <N57412320ed684a019fd87e117bf821a7> 
######## unexpected name: <N4c2201c9873b4efc97477957b5c8e3ce> 
######## unexpected name: <N37c37e0a00934ea3a0fe3fd92b49d85e> 
######## unexpected name: <Nc56df9f8f79f428696ae1310f39e2186> 
  


