__version__ = '1.3.0'

# DOCKER HUB
DOCKER_HUB_URL = 'hub.docker.zeblok.com/aimodel'
AI_PIPELINE_DOCKER_FOLDER = 'zeblok'

# AVAILABLE PLAN TYPES
PLAN_TYPE_WORKSTATION = 'Ai-WorkStation'
PLAN_TYPE_API = 'Ai-API'
PLAN_TYPE_CAAS = 'CAAS'
PLAN_TYPE_MICROSERVICE = 'Ai-MicroService'
PLAN_TYPE_ORCHESTRATION = 'Orchestration-Addon'

# MISCELLANEOUS
PRESIGNED_URL_EXPIRATION_SECS = 3600  # 1 hour
