
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-19T10:50:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74181e0adc2850f5d46297ff3f8cff48ad268c02",
 "version": "1.0.112"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
