# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: _/records/Protobuf.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    '_/records/Protobuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18_/records/Protobuf.proto\x12\t_.records\x1a google/protobuf/descriptor.proto:-\n\x02id\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\t:0\n\x05no_db\x12\x1f.google.protobuf.MessageOptions\x18\xd2\x86\x03 \x01(\x08:2\n\x07no_pkey\x12\x1f.google.protobuf.MessageOptions\x18\xd3\x86\x03 \x01(\x08:5\n\nno_handler\x12\x1f.google.protobuf.MessageOptions\x18\xd4\x86\x03 \x01(\x08:-\n\x04pkey\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08:-\n\x04uniq\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08:,\n\x03ref\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\t:/\n\x06paired\x12\x1d.google.protobuf.FieldOptions\x18\xd4\x86\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_.records.Protobuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
