import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_1bb79b6eb3(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_e9b62f7872():spartaqube_cli.list()
@app.command()
def sparta_dccaba327e():spartaqube_cli.sparta_dccaba327e()
@app.command()
def sparta_4763f37c43():print('Hello world!')
if __name__=='__main__':app()