# generated by datamodel-codegen:
#   filename:  asset_uri_download_v1.json

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    uri: AnyUrl
    """
    The URI on which to perform a download.  Includes a download ticket if make_ticket was true.
    """
