# coding: utf-8

"""
    DOCUMENTATION

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: contact-email@something.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dushibian_strapi_client.models.activity_created_by import ActivityCreatedBy
from dushibian_strapi_client.models.article_tags_data_inner_attributes_books_data_inner_attributes_cover_data_attributes_folder_data_attributes_files import ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributesFiles
from dushibian_strapi_client.models.shared_banner_component_image_data_attributes_related import SharedBannerComponentImageDataAttributesRelated
from typing import Optional, Set
from typing_extensions import Self

class ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributes(BaseModel):
    """
    ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributes
    """ # noqa: E501
    name: Optional[StrictStr] = None
    path_id: Optional[StrictInt] = Field(default=None, alias="pathId")
    parent: Optional[ActivityCreatedBy] = None
    children: Optional[SharedBannerComponentImageDataAttributesRelated] = None
    files: Optional[ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributesFiles] = None
    path: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    created_by: Optional[ActivityCreatedBy] = Field(default=None, alias="createdBy")
    updated_by: Optional[ActivityCreatedBy] = Field(default=None, alias="updatedBy")
    __properties: ClassVar[List[str]] = ["name", "pathId", "parent", "children", "files", "path", "createdAt", "updatedAt", "createdBy", "updatedBy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of parent
        if self.parent:
            _dict['parent'] = self.parent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of children
        if self.children:
            _dict['children'] = self.children.to_dict()
        # override the default output from pydantic by calling `to_dict()` of files
        if self.files:
            _dict['files'] = self.files.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "pathId": obj.get("pathId"),
            "parent": ActivityCreatedBy.from_dict(obj["parent"]) if obj.get("parent") is not None else None,
            "children": SharedBannerComponentImageDataAttributesRelated.from_dict(obj["children"]) if obj.get("children") is not None else None,
            "files": ArticleTagsDataInnerAttributesBooksDataInnerAttributesCoverDataAttributesFolderDataAttributesFiles.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "path": obj.get("path"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "createdBy": ActivityCreatedBy.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedBy": ActivityCreatedBy.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None
        })
        return _obj


