# coding: utf-8

"""
    DOCUMENTATION

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: contact-email@something.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dushibian_strapi_client.models.users_permissions_permissions_tree_value_controllers_value_value import UsersPermissionsPermissionsTreeValueControllersValueValue
from typing import Optional, Set
from typing_extensions import Self

class UsersPermissionsPermissionsTreeValue(BaseModel):
    """
    every api
    """ # noqa: E501
    controllers: Optional[Dict[str, Dict[str, UsersPermissionsPermissionsTreeValueControllersValueValue]]] = Field(default=None, description="every controller of the api")
    __properties: ClassVar[List[str]] = ["controllers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsersPermissionsPermissionsTreeValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in controllers (dict)
        _field_dict = {}
        if self.controllers:
            for _key_controllers in self.controllers:
                if self.controllers[_key_controllers]:
                    _field_dict[_key_controllers] = self.controllers[_key_controllers].to_dict()
            _dict['controllers'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsersPermissionsPermissionsTreeValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "controllers": dict(
                (_k, dict(
                    (_ik, UsersPermissionsPermissionsTreeValueControllersValueValue.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj.get("controllers").items()
            )
            if obj.get("controllers") is not None
            else None
        })
        return _obj


