# [SNOWFLAKE]
SNOWFLAKE_ACCOUNT="SNOWFLAKE_ACCOUNT"
SNOWFLAKE_DATABASE="SNOWFLAKE_DATABASE"
SNOWFLAKE_SCHEMA="SNOWFLAKE_SCHEMA"
SNOWFLAKE_WAREHOUSE="SNOWFLAKE_WAREHOUSE"
SNOWFLAKE_ROLE="SNOWFLAKE_ROLE"
SNOWFLAKE_USER="SNOWFLAKE_USER"
SNOWFLAKE_PASSWORD="SNOWFLAKE_PASSWORD"
SNOWFLAKE_HOST="SNOWFLAKE_HOST"
OAUTH_AUTHENTICATION = "oauth"

# [REDSHIFT]
REDSHIFT_HOST="REDSHIFT_HOST"
REDSHIFT_USERNAME="REDSHIFT_USERNAME"
REDSHIFT_PASSWORD="REDSHIFT_PASSWORD"
REDSHIFT_DATABASE="REDSHIFT_DATABASE"

# [POSTRESQL]
POSTGRESQL_HOST="POSTGRESQL_HOST"
POSTGRESQL_USERNAME="POSTGRESQL_USERNAME"
POSTGRESQL_PASSWORD="POSTGRESQL_PASSWORD"
POSTGRESQL_DATABASE="POSTGRESQL_DATABASE"

# [OTHER]