# Generated by CodiumAI
import wizard
from wizard._utils.data_loader import get_files_by_extension, make_path_absolute, to_cube, read

from wizard._core.datacube import DataCube

path = '/Users/flx/Documents/data/Tom_MA/2024_engels/Image.fsm'

# spec = specread(path)
dc = read(path)
print(dc.cube.shape)
print(len(dc.wavelengths))
wizard.plotter(dc)

assert dc.shape == (408, 381, 729)