from enum import Enum


class TaskSubtypeEnum(Enum):
    DEFAULT = "0"
    NORMAL_QS = "101"
    DOCUMENT_PARSING = "102"
    DATA_VISILIZATION = "103"
    PICTURE_2_TABLE = "104"

    DOCUMENT_STRUCTURE_MATHPIX = "501"
    DOCUMENT_STRUCTURE_ZJ = "502"
    DOCUMENT_EXTRACTION_LLM = "503"
    DOCUMENT_EXTRACTION_ZJ = "504"
    PLUGIN_CHOSEN = "505"
    PARAMETERS_EXTRACTION = "506"

