
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-13T04:41:44+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd119757ce824380a72678a12af78ba9dcd6b9be",
 "version": "1.60"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
