# coding: utf-8

"""
    Simple Game Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tangled_game_client.models.make_move403_response import MakeMove403Response

class TestMakeMove403Response(unittest.TestCase):
    """MakeMove403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MakeMove403Response:
        """Test MakeMove403Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MakeMove403Response`
        """
        model = MakeMove403Response()
        if include_optional:
            return MakeMove403Response(
                success = False,
                message = 'Invalid move',
                details = 'The move is not allowed in the current game state'
            )
        else:
            return MakeMove403Response(
        )
        """

    def testMakeMove403Response(self):
        """Test MakeMove403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
