# coding: utf-8

"""
    Simple Game Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tangled_game_client.models.get_scorers200_response import GetScorers200Response

class TestGetScorers200Response(unittest.TestCase):
    """GetScorers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetScorers200Response:
        """Test GetScorers200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetScorers200Response`
        """
        model = GetScorers200Response()
        if include_optional:
            return GetScorers200Response(
                scorers = ["precomputed","schrodinger","qc"]
            )
        else:
            return GetScorers200Response(
        )
        """

    def testGetScorers200Response(self):
        """Test GetScorers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
